# utils.py (or place in indicators.py)

import re
import logging # Optional: for internal logging if needed

logger = logging.getLogger(__name__) # Optional: get logger for this module

def parse_edit_comment(comment_string):
    """
    Parses a Wikidata edit comment string to extract structured information.

    Attempts to identify standard patterns generated by the Wikibase UI,
    common tools (like QuickStatements), and revert/undo actions.

    Args:
        comment_string (str): The edit comment text.

    Returns:
        dict: A dictionary containing parsed information, with keys like:
              'action' (str): Standard action verb (e.g., 'wbsetclaim', 'wbsetlabel', 'undo')
                              or 'manual', 'unknown'.
              'property_id' (str|None): Extracted property ID (e.g., 'P31').
              'language' (str|None): Extracted language code (e.g., 'en').
              'is_standard' (bool): True if a known standard pattern was matched.
              'details' (dict): Contains other extracted info:
                  'claim_value_qid' (str|None): QID used as a claim value (e.g., 'Q5').
                  'merge_target_qid' (str|None): Target QID for merges (e.g., 'Q123').
                  'alias_value' (str|None): Alias text added/removed.
                  'sitelink_site' (str|None): Sitelink site ID (e.g., 'enwiki').
                  'undone_rev_id' (int|None): Revision ID being undone.
                  'reverted_user' (str|None): User being reverted.
                  'tool_name' (str|None): Identified tool name (e.g., 'QuickStatements').
                  'raw_details' (str|None): Raw detail string from comment if specific parsing failed.
                  'manual_comment_part' (str|None): Text following the /* ... */ block.
                  'manual_comment' (str|None): The full comment if determined to be manual.
    """
    # Default return value for unknown/manual/empty comments
    # Note: Removed top-level target_qid
    default_result = {'action': 'unknown', 'property_id': None, 'language': None,
                      'is_standard': False, 'details': {}}

    if not comment_string:
        return default_result

    comment_string = comment_string.strip()
    is_standard = False
    result = default_result.copy() # Start with default
    result['details'] = {} # Ensure details dict is initialized

    # --- Regex patterns ---
    # Most specific first
    claim_qid_inside_match = re.match(r'/\* (wbsetclaim-update|wbcreateclaim-create):([P]\d+)\[\[([Qq]\d+)\]\]', comment_string, re.IGNORECASE)
    merge_match = re.match(r'/\* (wbmergeitems-to):(\d+)\|([Qq]\d+) \*/', comment_string, re.IGNORECASE)
    remove_claim_match = re.match(r'/\* (wbremoveclaims-remove):(\d+)\|([P]\d+) \*/', comment_string, re.IGNORECASE)
    alias_match = re.match(r'/\* (wbsetaliases-\w+):(\d+)\|([a-z-]+)(?:\|(.*))? \*/', comment_string, re.IGNORECASE)
    sitelink_match = re.match(r'/\* (wbsetsitelink-\w+):(\d+)\|([a-z_]+wiki) \*/', comment_string, re.IGNORECASE)
    # General standard comment pattern (catches the /* action:details */ part and any following text)
    std_comment_match = re.match(r'/\* ([-a-z0-9|:]+?) \*/(.*)', comment_string, re.IGNORECASE)
    # Pattern to extract Property and QID from the trailing part like "[[Property:Pxx]]: [[Qyy]]"
    prop_qid_trailing_match = re.compile(r'\[\[Property:([Pp]\d+)\]\]:\s*\[\[([Qq]\d+)\]\]')

    # --- Patterns for Revert/Undo ---
    undo_match = re.match(r'Undo revision (\d+)', comment_string)
    revert_match = re.match(r'Reverted edits by ([^ ]+)', comment_string)

    # --- Patterns for Tools ---
    qs_match = re.search(r'(?:via|using)\s+QuickStatements', comment_string, re.IGNORECASE)


    # --- Processing Matches (Order might matter) ---

    if claim_qid_inside_match:
        # Handles /* wbsetclaim...:Pxxx[[Qyyy]] */
        is_standard = True
        result['action'] = claim_qid_inside_match.group(1).lower()
        result['property_id'] = claim_qid_inside_match.group(2).upper()
        result['details']['claim_value_qid'] = claim_qid_inside_match.group(3).upper()
    elif merge_match:
        is_standard = True
        result['action'] = merge_match.group(1).lower()
        # Moved target QID to details
        result['details']['merge_target_qid'] = merge_match.group(3).upper()
    elif remove_claim_match:
        is_standard = True
        result['action'] = remove_claim_match.group(1).lower()
        result['property_id'] = remove_claim_match.group(3).upper()
    elif alias_match:
        is_standard = True
        result['action'] = alias_match.group(1).lower()
        result['language'] = alias_match.group(3).lower()
        if alias_match.group(4): # If alias text was captured
             result['details']['alias_value'] = alias_match.group(4).strip()
    elif sitelink_match:
         is_standard = True
         result['action'] = sitelink_match.group(1).lower()
         result['details']['sitelink_site'] = sitelink_match.group(3).lower()
    elif std_comment_match:
        # General pattern /* action:details */ maybe followed by more text
        is_standard = True
        action_part = std_comment_match.group(1).strip()
        manual_part = std_comment_match.group(2).strip() # Text after the /* ... */

        # Split the action part e.g., "wbsetclaim-create:2||1" or "wbsetlabel-set:1|en"
        action_details_split = action_part.split(':', 1)
        action_verb = action_details_split[0].lower()
        raw_details = action_details_split[1] if len(action_details_split) > 1 else ''

        result['action'] = action_verb
        result['details']['raw_details'] = raw_details # Store the part after the first colon

        if manual_part:
            result['details']['manual_comment_part'] = manual_part
            # NEW: Check if the manual part contains the [[Property:Pxx]]: [[Qyy]] pattern
            pq_match = prop_qid_trailing_match.search(manual_part)
            if pq_match:
                 result['property_id'] = pq_match.group(1).upper()
                 result['details']['claim_value_qid'] = pq_match.group(2).upper()
                 # If we found P/Q here, maybe clear the less specific raw_details? Optional.
                 # result['details']['raw_details'] = None

        # Further parse raw_details for common cases if not handled by pq_match
        if not result['property_id'] and (action_verb.startswith('wbsetclaim') or action_verb.startswith('wbcreateclaim')):
            # Example: Check raw_details like "P31" or "1|P31"
            detail_parts = raw_details.split('|')
            prop_candidate = detail_parts[-1] # Often the last part
            if prop_candidate.upper().startswith('P') and prop_candidate[1:].isdigit():
                 result['property_id'] = prop_candidate.upper()

        elif not result['language'] and (action_verb.startswith('wbsetlabel') or action_verb.startswith('wbsetdescription') or action_verb.startswith('wbsetaliases')):
             # Example: Check raw_details like "1|en" or "en"
             detail_parts = raw_details.split('|')
             # Language code is often the last part if numbers are present, or the only part
             lang_candidate = detail_parts[-1]
             # Basic check for 2-3 letter language codes (can be improved)
             if 2 <= len(lang_candidate) <= 3 and lang_candidate.islower():
                  result['language'] = lang_candidate

    # --- Check Non-Standard but Common Patterns ---
    elif undo_match:
        is_standard = False # Treat as semi-standard/manual action
        result['action'] = 'undo'
        try:
            result['details']['undone_rev_id'] = int(undo_match.group(1))
        except ValueError:
            logger.warning(f"Could not parse revision ID from undo comment: {comment_string}")
    elif revert_match:
         is_standard = False # Treat as semi-standard/manual action
         result['action'] = 'revert'
         result['details']['reverted_user'] = revert_match.group(1)

    # --- Check Tool Info ---
    if qs_match:
        result['details']['tool_name'] = 'QuickStatements'

    # --- Final determination if no standard pattern matched ---
    if not is_standard and result['action'] == 'unknown':
         if comment_string.startswith('/*') and comment_string.endswith('*/'):
             result['action'] = 'other_auto'
             result['details']['raw_details'] = comment_string[2:-2].strip()
         else:
             result['action'] = 'manual'
             result['details']['manual_comment'] = comment_string

    result['is_standard'] = is_standard
    return result

# --- Example Usage (for testing) ---
if __name__ == '__main__':
    comments = [
        "/* wbsetlabel-set:1|en */ test label",
        "/* wbsetclaim-update:P31 */",
        "/* wbsetclaim-update:P18[[Q12345]] */",
        "/* wbcreateclaim-create:P569[[Q6789]] */",
        "/* wbremoveclaims-remove:1|P569 */",
        "/* wbmergeitems-to:1|Q987 */",
        "/* wbsetaliases-add:1|de|New Alias */",
        "/* wbsetsitelink-add:1|frwiki */",
        "/* wbsetclaim-create:2||1 */ [[Property:P25]]: [[Q4115189]]", # <-- New test case
        "Undo revision 123456 by SomeUser",
        "Reverted edits by BadActor (talk | contribs)",
        "Added statement using QuickStatements",
        "fixed typo",
        "",
        None,
        "/* some other auto comment */",
    ]
    print(f"--- Testing parse_edit_comment ---")
    for c in comments:
        print(f"Comment: {c}")
        parsed = parse_edit_comment(c)
        print(f"Parsed: {parsed}\n")
    print(f"--- End Testing ---")